return Def.ActorFrame{
	Def.ActorFrame{
		GainFocusCommand=function(self)
			setenv("advMode","Comboch");
		end;
	};
	Def.ActorFrame{
		OnCommand=cmd(x,SCREEN_RIGHT+139;y,SCREEN_CENTER_Y+25;diffusealpha,0;sleep,.301;decelerate,.367;x,SCREEN_CENTER_X-129;diffusealpha,1);
		OffCommand=cmd(sleep,.034;decelerate,.133;addx,-32;addy,-12;accelerate,.2;x,SCREEN_RIGHT+139;addy,-5;diffusealpha,0);
		GainFocusCommand=cmd(stoptweening;linear,.1;x,SCREEN_CENTER_X-144;linear,.1;x,SCREEN_CENTER_X-129);
		--BG Picture
		LoadActor("_advanced/combo_in")..{
			OnCommand=cmd(x,24;y,4);
			GainFocusCommand=cmd(diffusealpha,0);
			LoseFocusCommand=cmd(diffusealpha,1);
		};
		LoadActor("_advanced/combo_ac")..{
			OnCommand=cmd(x,24;y,4);
			GainFocusCommand=cmd(diffusealpha,1);
			LoseFocusCommand=cmd(diffusealpha,0);
		};
		--BG Frame
		LoadActor("_advanced/inactive_bg")..{
			GainFocusCommand=cmd(diffusealpha,0);
			LoseFocusCommand=cmd(diffusealpha,1);
		};
		LoadActor("_advanced/active_bg")..{
			GainFocusCommand=cmd(diffusealpha,1);
			LoseFocusCommand=cmd(diffusealpha,0);
		};
		--Icon
		LoadActor("_advanced/prev_com")..{
			OnCommand=cmd(x,-108;y,-36);
			GainFocusCommand=cmd(diffusealpha,0);
			LoseFocusCommand=cmd(diffusealpha,.5);
		};
		LoadActor("_advanced/icon_com")..{
			OnCommand=cmd(x,-108;y,-36);
			GainFocusCommand=cmd(diffusealpha,1);
			LoseFocusCommand=cmd(diffusealpha,0);
		};
		--Title
		LoadActor("_advanced/tit_com_ac")..{
			OnCommand=cmd(x,22;y,-47);
			GainFocusCommand=cmd(diffusealpha,1);
			LoseFocusCommand=cmd(diffusealpha,0);
		};
		LoadActor("_advanced/tit_com_in")..{
			OnCommand=cmd(x,22;y,-47);
			GainFocusCommand=cmd(diffusealpha,0);
			LoseFocusCommand=cmd(diffusealpha,.5);
		};
	};
	LoadActor(THEME:GetPathS("ScreenAdvanced","comboch"))..{
		GainFocusCommand=cmd(play);
		LoseFocusCommand=cmd(stop);
	};
	Def.ActorFrame{
		OnCommand=cmd(x,SCREEN_CENTER_X;y,SCREEN_BOTTOM-82);
		Def.ActorFrame{
			OffCommand=cmd(sleep,.133;linear,.067;y,29;zoomy,0);
			LoadActor(THEME:GetPathG("Shared","frame"))..{
				OnCommand=cmd(cropright,.7;cropbottom,.7;x,-280;y,-21);
			};
			LoadActor(THEME:GetPathG("Shared","frame"))..{
				OnCommand=cmd(cropleft,.3;cropright,.3;cropbottom,.7;y,-21;zoomto,576*2.5,12*3.3);
			};
			LoadActor(THEME:GetPathG("Shared","frame"))..{
				OnCommand=cmd(cropleft,.7;cropbottom,.7;x,280;y,-21);
			};
		};
		Def.ActorFrame{
			OffCommand=cmd(sleep,.133;linear,.067;zoomy,0);
			LoadActor(THEME:GetPathG("Shared","frame"))..{
				OnCommand=cmd(cropright,.7;croptop,.3;cropbottom,.3;x,-279;zoomto,12*3.5,58*2.5);
			};
			LoadActor(THEME:GetPathG("Shared","frame"))..{
				OnCommand=cmd(croptop,.3;cropbottom,.3;cropleft,.3;cropright,.3;zoomto,100*14.35,20*7.3);
			};
			LoadActor(THEME:GetPathG("Shared","frame"))..{
				OnCommand=cmd(cropleft,.7;croptop,.3;cropbottom,.3;x,279;zoomto,12*3.5,58*2.5);
			};
		};
		Def.ActorFrame{
			OffCommand=cmd(sleep,.133;linear,.067;y,-29;zoomy,0);
			LoadActor(THEME:GetPathG("Shared","frame"))..{
				OnCommand=cmd(cropright,.7;croptop,.7;x,-280;y,21);
			};
			LoadActor(THEME:GetPathG("Shared","frame"))..{
				OnCommand=cmd(cropleft,.3;cropright,.3;croptop,.7;y,21;zoomto,576*2.5,12*3.3);
			};
			LoadActor(THEME:GetPathG("Shared","frame"))..{
				OnCommand=cmd(cropleft,.7;croptop,.7;x,280;y,21);
			};
		};
		LoadFont("sys_desc")..{
			Text=ScreenString("ComboChText");
			OnCommand=cmd(diffusealpha,0;x,-283;y,-26);
			AnimCommand=cmd(x,-293;y,-26;horizalign,left;vertalign,top;zoom,.75;diffusealpha,0;linear,.134;diffusealpha,.6;x,-283);
			OffCommand=cmd(linear,.167;diffusealpha,0;x,-293);
			GainFocusCommand=cmd(stoptweening;queuecommand,"Anim");
		};
		LoadFont("sys_desc")..{
			Text=ScreenString("ComboChText");
			OnCommand=cmd(diffusealpha,0;x,-283;y,-26);
			AnimCommand=cmd(x,-263;y,-26;horizalign,left;vertalign,top;zoom,.75;diffusealpha,0;linear,.134;diffusealpha,.6;x,-283);
			OffCommand=cmd(linear,.167;diffusealpha,0;x,-263);
			GainFocusCommand=cmd(stoptweening;queuecommand,"Anim");
		};
		GainFocusCommand=cmd(diffusealpha,1);
		LoseFocusCommand=cmd(diffusealpha,0);
	};
};