return Def.ActorFrame {
	LoadActor(THEME:GetPathG("","_style/info_ver"))..{
		OnCommand=cmd(x,SCREEN_CENTER_X+75;y,SCREEN_CENTER_Y-51);
	};
	Def.ActorFrame{
		GainFocusCommand=cmd(diffusealpha,1);
		LoseFocusCommand=cmd(diffusealpha,0);
		LoadActor(THEME:GetPathG("Common","wheel/bnbg"))..{
			OnCommand=cmd(x,61;y,53;zoomto,273,85);
		};
		LoadActor(THEME:GetPathG("","_style/icon_pad"))..{
			OnCommand=cmd(x,4;y,53);
		};
		LoadActor(THEME:GetPathG("","_style/icon_pad"))..{
			OnCommand=cmd(x,103;y,53);
		};
		LoadActor(THEME:GetPathG("Common","wheel/banner"))..{
			OnCommand=cmd(x,100;y,219);
		};
		LoadActor("Art")..{
			InitCommand=cmd(Center;addx,-251;addy,36);
		};
		LoadActor(THEME:GetPathG("","_style/ver_scan"))..{
			OnCommand=cmd(x,SCREEN_CENTER_X-71;y,SCREEN_CENTER_Y-51);
		};
	};
}
